version: "3.2"

services:
  mariadbnodejs:
    image: mariadb:latest
    container_name: mariadbnodejs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: default_schema
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbnodejs/mysql/data/:/var/lib/mysql/ # data storage
    networks:
      - default 

volumes:
  dbnodejs:
    driver: local
    driver_opts:
      type: disk
      size: 5GB
      device: ""

networks:
  default:
    driver: bridge
